### ISSUE TITLE
Folder renaming for ease of installation scripts

### ISSUE THREAD

**Issue by ShayBox** [MiguelRAvila/McConceptX-Customized-Theme#2]
`Aurorae` > `aurorae/themes/McManjaro`
`Color Scheme` > `color-schemes/McManjaro`
`Plasma` > `plasma/look-and-feel/com.github.miguelravila.mcmanjaro`
`Kvantum` > `Kvantum/McManjaro`

**Comment by migueravila** [comment]
What a great idea! I'll make the changes! Thanks!

**Comment by migueravila** [comment]
@ShayBox Done! If you have any other suggestion make it!

**Comment by ShayBox** [comment]
Do you have any icon pack or gtk theme you prefer with the theme

**Comment by migueravila** [comment]
W O W. I Use this iconPack: https://store.kde.org/p/1305429/ (With the green configuration) And about the GTK theme I use this one for a better compatibility with the windows: https://www.gnome-look.org/p/1319454/
About the Konsole I've just uploaded it!

And... Thank you very  much about the AUR Package, That's amazing man! For real! You're amazing I'll put it in the Readme

**Comment by ShayBox** [comment]
you have to rename `DarkPastels.colorscheme` to something that doesn't come pre-installed on kde :p

Thank you, I love the theme.

**Comment by migueravila** [comment]
I thought I changed it, Done! Man, Thank you so much!

**Comment by ShayBox** [comment]
No problem

**Comment by migueravila** [comment]
I'll close the issue, once again Thank you!
